Scripts/audio.py
Scripts/bookshelfAPI.py
Scripts/main.py

Fix for issue #4

---

Scripts/administration.py
Scripts/audio.py
Scripts/bookshelfAPI.py
Scripts/main.py
Scripts/settings.py
Scripts/subscription_task.py
Scripts/wishlist.py

Fixed all methods which weren't async to async in bookshelfAPI. Also, made log easier to read. Added time stamp.

Fixed: ASYNC Primary HTTPX Connections

---

Scripts/settings.py
Scripts/subscription_task.py

Tasks Finalized

---

Dockerfile
Scripts/audio.py
Scripts/multi_user.py
Scripts/subscription_task.py

Changed to bookworm-slim and minor fixes

Change docker image 

---

Scripts/bookshelfAPI.py
Scripts/wishlist.py

Fixed many small bugs related to wishlists and also made it so that a user can dynamically switch between books when using the /add-book command.

FIX & ENHANCEMENT: Dynamic select menu

---

Scripts/audio.py
Scripts/requirements.txt
Scripts/settings.py

Removed hot fix and bumped the interactions package to 5.13.2

Beta V1.2.5

---

Scripts/audio.py
Scripts/settings.py

all major bugs have been removed.

Removing Beta Tag

---

Scripts/wishlist.py

Addded /view-all-wishlists

---

Scripts/wishlist.py

Added missing arg for new admin wishlist command

HOTFIX: Added missing arg for new admin wishlist command

---

Scripts/wishlist.py

Requestor information will now show up (if possible) on embed when using admin wishlist command.

Added requestor info to embed

---

Scripts/db_additions.py
Scripts/main.py
Scripts/settings.py
Scripts/subscription_task.py
Scripts/wishlist.py

added downloaded column to wishlist table, with this I added a future proof method to main.py to allow backwards compatibility with older versions when updating.

Added new column to wishlist

---

Scripts/main.py
Scripts/subscription_task.py
Scripts/wishlist.py

minor change

---

Scripts/wishlist.py

view-all-wishlist now displays the download status of the item.

Added download status to /view-all-wishlists command

---

Scripts/wishlist.py

reset vars when nudge is complete

---

Scripts/audio.py
Scripts/main.py
Scripts/multi_user.py
Scripts/settings.py

- Added auto kill session warning message. 
- Message will self destruct if playback resumes after 60 seconds.
- moved dependency import for better log readability

Version 1.2.7

---

Scripts/administration.py

added await to user_search_autocomplete

---

Scripts/subscription_task.py

Added colors for new book check command and also the ability to override the new book task embed.

Minor Enhancement: Colors!

---

Scripts/audio.py
Scripts/bookshelfAPI.py
Scripts/default_commands.py
Scripts/multi_user.py
Scripts/settings.py

Fixed bug where character limit would stop choices from populating. Also, simplified overall embeds for most of the older commands.

Character Limit Bug Fix

---

Scripts/main.py
Scripts/settings.py

Added CLIENT_ID to the env vars, when populated, it will generate a customized join link for your bot.

CLIENT_ID and Startup guild invite link

---

Dockerfile
Scripts/healthcheck.py
Scripts/multi_user.py
Scripts/settings.py

Added healthcheck.py and healthcheck to dockerfile.

Healthcheck

---

Scripts/audio.py

Added session limit and cleaned up audio.py

Audio.py cleanup

---

Dockerfile
Scripts/requirements.txt
Scripts/settings.py

Minor Updates

---

Scripts/bookshelfAPI.py

Added status code checks before parsing JSON.
Improved error handling for missing or invalid API responses.
Optimized Audio File Selection:
Replaced loop with next() for efficient file lookup.
Defaults to the first audio file if the requested index_id isn't found.
Improved Logging & Debugging:
Added warnings for missing environment variables.
Logs errors for failed API calls and missing data fields.
Code Cleanup & Readability:
Reduced redundant assignments.
Improved dictionary key lookups using .get() to prevent crashes.

Enhanced API Response Handling & Minor Fixes

---

Scripts/audio.py
Scripts/default_commands.py
Scripts/subscription_task.py
Scripts/wishlist.py

When OPT_IMAGE_URL is set, use that for links in embeds.

Use HTTPS for Book Links

---

Scripts/audio.py
Scripts/bookshelfAPI.py
Scripts/main.py
Scripts/settings.py
Scripts/subscription_task.py

Added task to check for finished books. Must be setup using /setup-tasks command, similar to recently finished book command.

Finished Book Check 

---

Scripts/bookshelfAPI.py
Scripts/settings.py
Scripts/subscription_task.py
Scripts/wishlist.py

Fixed default provider and added ability to search for a specific user with /wishlist command.

Wishlist Module Update

---

Scripts/main.py
Scripts/settings.py
Scripts/subscription_task.py
Scripts/wishlist.py

You will now be able to assign a user to a task to allow admin tasks to run in the background.

Added user to task subscriptions

---

Scripts/default_commands.py

Not really a fan of the error responses in discord so here's a little safety check to make it more friendly.

Provide ping with a safety check

---

Scripts/audio.py

Random book selection was broken. Moved it from autocomplete section to audio_play section, it was hammering the server while in the autocomplete section, typing each letter was making a whole new selection. Changed Force to startover to make it more clearly show what it's designed for, with that, i added logic to reset the book time to zero instead of relying on the ABS server to do it, this way you can reset the book whenever you desire.

Fix random book selection and playback issues

---

Scripts/audio.py

cleaned up recent sessions auto complete. podcast items still technically appear in this list, but since i intend to add support, dont want to spend time worrying about filtering them here.

Add playability check to autocomplete to filter broken items

---

Scripts/audio.py
Scripts/ui_components.py

Moved UI Components to their own ui_components.py file. Went ahead and added the Series play book and the Podcast play books in preparation of adding their support. For Series, they would act like a playlist, so if you finish book 1 and ABS has them in a Series, it will automatically start Book 2. Could possibly add a enable/disable button next to the Series buttons in case the behavior isn't wanted.
For the play command, i was thinking /play all | book | series | podcast 
could expand it to /play all | book | series | podcast | author | genre

Move UI Components

---

Scripts/audio.py

Stream would crash if user attempted to change chapters while the book had no chapter data.

Fix chapter null checks for books without chapter data

---

Scripts/audio.py

When I redid the design for the chapter respecting boundaries, i just retested it at the chapter boundary, making sure it respected the expected behavior. In normal rewinding mode though it was failing to set nextTime and was passing a None value causing the stream to crash.

Fix None nextTime while rewinding

---

Scripts/audio.py
Scripts/bookshelfAPI.py
Scripts/default_commands.py

Updated book time formats to use 00:00:00 and fixed some consistency issues across the play cards.

Update Book Time Format

---

Scripts/audio.py

Was receiving rate limiting errors at the 1 hour mark from the announce card.
WARNING - 20:00:33 : PATCH /channels/11111111/messages/{message_id} Has exceeded its ratelimit (5)! Reset in 1.0 seconds
Now updates every 10 or 15 seconds and the error is gone

ratelimit announce card to 10 seconds

---

Scripts/audio.py
Scripts/bookshelfAPI.py

There was a regression where once a session had ended, it didn't kill the stream and just hung there. I haven't figured out exactly which PR caused it, I suspect some error handling fixing might've allowed the bug to surface since the sessions were ending most likely via silently failing. I went ahead and redid the cleanup system to fix the issue and created the bookshelf API methods to mark a book as unfinished or as finished. Made sure that move_chapter and skip forward also respected the end of book logic. I added a 30 second check at the end of a book in session_update in case ABS marks a book finished before the stream is actually finished to ensure that the stream doesn't prematurely stop, i was having that issue in a few of the versions I made while testing.

Session cleanup

---

Scripts/default_commands.py

Search was failing, suspect it was due to None values. It now passes only known values.

fix search book
